baseURL                   = "https://gauravmishra.netlify.com"
builddrafts                = false
languageCode               = "en"
canonifyurls               = true
contentdir                 = "content"
layoutdir                  = "layouts"
publishdir                 = "public"
enableEmoji                = true
hasCJKLanguage             = true
summaryLength              = 200
Paginate                   = 3

theme                      = "AllinOne"
title                      = "Gaurav Mishra"

pygmentsuseclasses         = true


[permalinks]
  blog                     = "blog/:year-:month/:slug/"


[taxonomies]
  tag                      = "tags"
  series                   = "series"
  category                 = "categories"


[menu]
  [[menu.main]]
    name                   = "About"
    weight                 = -120
    identifier             = "about"
    url                    = "about/"  

  [[menu.main]]
    name                   = "Projects"
    weight                 = -110
    identifier             = "project"
    url                    = "project/" 

  [[menu.main]]
    name                   = "Articles"
    weight                 = -100
    identifier             = "article"
    url                    = "article/"  

 
  [[menu.main]]
    name                   = "Pfeature"
    weight                 = -100
    identifier             = "pfeature"
    url                    = "https://webs.iiitd.edu.in/raghava/pfeature/"  

  [[menu.main]]
    name                   = "CV"
    weight                 = -80
    identifier             = "cv"
    url                    = "CV_Gaurav_Mishra.pdf"  
    
    [[menu.main]]
    name                   = "Classical Music"
    weight                 = -80
    identifier             = "music"
    url                    = "music/"  


[params]
  faviconfile              = "avatar.png"               # from static/
  avatar                   = "gaurav_dp2.jpeg"             # path to image in static dir e.g img/avatar.png 
  author                   = "Gaurav"
  description              = ["Deep Learning Enthusiast", "ECE Graduate.", "Hindustani Classical Vocalist."]           # appears in the site header when set to a non-empty string
  welcome_head             = "Hello Visitor"
  welcome_word             = "~Recent Posts~"

  latestpostscount         = 2                             # how many posts to display on the home page
  bloggroupby              = 'month'
  dateform                 = "Jan 2, 2019"
  dateformfull             = "2006-01-02  Monday  15:04:05"
  noshowreadtime           = false                         # if true, don't show "<x> minutes read" in posts

  # slides
  slidesDirPath            = "static/header-slides"    # path to image in local dir (path for hugo)
  slidesDirPathURL         = "header-slides"    # path to image in static dir (for static pages)

  # highlighting 
  highlightjs              = true

  # latex
  katex                    = true

  # links
  email                    = "in.gaurav.mishra@email.com"
  github                   = "//github.com/mishragauravgm"
  linkedin                 = "//www.linkedin.com/in/gauravmishra1234/"
  instagram                = "//www.instagram.com/mishraa_gaurav"
  researchgate             ="//www.researchgate.net/Gaurav_Mishra52"
  include_rss              = false                          # include RSS <link> tag in <head> and show RSS 
  scholar                  = "//scholar.google.co.in/citations?user=gdi0oOMAAAAJ&hl=en&authuser=3"  

  
  # analytics
  googleAnalytics          = "your-google-analytic-id"
    
    
